export const valoresProvincias = [
  {
    titulo: "GRUPO ETICA",
    key: "grupoEtica",
    id: 1,
    datos: [
      { province: "Buenos Aires", value: 44.24, opacity: 44.24 },
      { province: "CABA", value: 85.06, opacity: 85.06 },
      { province: "Catamarca", value: 12.49, opacity: 12.49 },
      { province: "Chaco", value: 51.50, opacity: 51.50 },
      { province: "Chubut", value: 51.81, opacity: 51.81 },
      { province: "Córdoba", value: 31.91, opacity: 31.91 },
      { province: "Corrientes", value: 40.73, opacity: 40.73 },
      { province: "Entre Ríos", value: 47.02, opacity: 47.02 },
      { province: "Formosa", value: 7.73, opacity: 7.73 },
      { province: "Jujuy", value: 70.56, opacity: 70.56 },
      { province: "La Pampa", value: 56.23, opacity: 56.23 },
      { province: "La Rioja", value: 36.58, opacity: 36.58 },
      { province: "Mendoza", value: 78.39, opacity: 78.39 },
      { province: "Misiones", value: 28.03, opacity: 28.03 },
      { province: "Neuquén", value: 46.95, opacity: 46.95 },
      { province: "Río Negro", value: 47.71, opacity: 47.71 },
      { province: "Salta", value: 22.03, opacity: 22.03 },
      { province: "San Luis", value: 40.73, opacity: 40.73 },
      { province: "San Juan", value: 26.46, opacity: 26.46 },
      { province: "Santa Cruz", value: 51.30, opacity: 51.30 },
      { province: "Santa Fe", value: 53.92, opacity: 53.92 },
      { province: "Santiago del Estero", value: 31.76, opacity: 31.76 },
      { province: "Tierra del Fuego", value: 33.42, opacity: 33.42 },
      { province: "Tucumán", value: 21.03, opacity: 21.03 },
      { province: "Nación", value: 82.95, opacity: 82.95 },
    ],
  },

  {
    titulo: "ÉTICA PÚBLICA",
    subTitulo: 'Normativa y sanciones previstas.',
    key: "eticaPublica",
    id: 2,
    datos: [
      { province: "Buenos Aires", value:0.00 },
      { province: "CABA", value: 100.00 },
      { province: "Catamarca", value:0.00 },
      { province: "Chaco", value: 100.00 },
      { province: "Chubut", value: 82.35 },
      { province: "Córdoba", value: 0.00 },
      { province: "Corrientes", value: 100.00 },
      { province: "Entre Ríos", value: 0.00 },
      { province: "Formosa", value: 0.00 },
      { province: "Jujuy", value: 82.35 },
      { province: "La Pampa", value: 0.00 },
      { province: "La Rioja", value: 82.35 },
      { province: "Mendoza", value: 100.00 },
      { province: "Misiones", value: 82.35 },
      { province: "Neuquén", value: 0.00 },
      { province: "Río Negro", value: 100.00 },
      { province: "Salta", value: 0.00 },
      { province: "San Luis", value: 0.00 },
      { province: "San Juan", value: 100.00 },
      { province: "Santa Cruz", value: 100.00 },
      { province: "Santa Fe", value: 100.00 },
      { province: "Santiago del Estero", value: 100.00 },
      { province: "Tierra del Fuego", value: 0.00 },
      { province: "Tucumán", value: 0.00 },
      { province: "Nación", value: 100.00 },
    ],
  },
  {
    titulo: "REGISTROS de gestión de intereses",
    subTitulo: 'Registro de regalos, viajes y reuniones.',
    key: "registrosDeGestionDeIntereses",
    id: 3,
    datos: [
      { province: "Buenos Aires", value: 0.00 },
      { province: "CABA", value: 0.00 },
      { province: "Catamarca", value: 0.00 },
      { province: "Chaco", value: 0.00 },
      { province: "Chubut", value: 0.00 },
      { province: "Córdoba", value: 0.00 },
      { province: "Corrientes", value: 0.00 },
      { province: "Entre Ríos", value: 0.00 },
      { province: "Formosa", value: 0.00 },
      { province: "Jujuy", value: 0.00 },
      { province: "La Pampa", value: 0.00 },
      { province: "La Rioja", value: 0.00 },
      { province: "Mendoza", value: 31.25 },
      { province: "Misiones", value: 0.00 },
      { province: "Neuquén", value: 0.00 },
      { province: "Río Negro", value: 0.00 },
      { province: "Salta", value: 0.00 },
      { province: "San Luis", value: 0.00 },
      { province: "San Juan", value: 0.00 },
      { province: "Santa Cruz", value: 0.00 },
      { province: "Santa Fe", value: 0.00 },
      { province: "Santiago del Estero", value: 0.00 },
      { province: "Tierra del Fuego", value: 0.00 },
      { province: "Tucumán", value: 0.00 },
      { province: "Nación", value: 62.50 },
    ],
  },
  {
    titulo: "DECLARACIONES JURADAS",
    subTitulo: 'Normativa, accesibilidad y sanciones.',
    key: "declaracionesJuradas",
    id: 4,
    datos: [
      { province: "Buenos Aires", value: 83.33 },
      { province: "CABA", value: 100.00 },
      { province: "Catamarca", value: 53.70 },
      { province: "Chaco", value: 100.00 },
      { province: "Chubut", value: 53.70 },
      { province: "Córdoba", value: 81.48 },
      { province: "Corrientes", value: 53.70 },
      { province: "Entre Ríos", value: 98.15 },
      { province: "Formosa", value: 20.37 },
      { province: "Jujuy", value: 100.00 },
      { province: "La Pampa", value: 46.30 },
      { province: "La Rioja", value: 37.04 },
      { province: "Mendoza", value: 100.00 },
      { province: "Misiones", value: 0.00 },
      { province: "Neuquén", value: 51.85 },
      { province: "Río Negro", value: 53.70 },
      { province: "Salta", value: 51.85 },
      { province: "San Luis", value: 35.19 },
      { province: "San Juan", value: 53.70 },
      { province: "Santa Cruz", value: 53.70 },
      { province: "Santa Fe", value: 51.85 },
      { province: "Santiago del Estero", value: 53.70 },
      { province: "Tierra del Fuego", value: 53.70 },
      { province: "Tucumán", value: 51.85 },
      { province: "Nación", value: 53.70 },
    ],
  },
  {
    titulo: "ACCESO AL EMPLEO PÚBLICO",
    subTitulo: 'Normativa, nóminas de personal, escalas salariales.',
    key: "accesoAlEmpleoPublico",
    id: 5,
    datos: [
      { province: "Buenos Aires", value: 23.81 },
      { province: "CABA", value: 95.24 },
      { province: "Catamarca", value: 0.00 },
      { province: "Chaco", value: 57.14 },
      { province: "Chubut", value: 57.14 },
      { province: "Córdoba", value: 61.90 },
      { province: "Corrientes", value: 57.14 },
      { province: "Entre Ríos", value: 42.86 },
      { province: "Formosa", value: 14.29 },
      { province: "Jujuy", value: 95.24 },
      { province: "La Pampa", value: 100.00 },
      { province: "La Rioja", value: 19.05 },
      { province: "Mendoza", value: 47.62 },
      { province: "Misiones", value: 14.29 },
      { province: "Neuquén", value: 100.00 },
      { province: "Río Negro", value: 90.48 },
      { province: "Salta", value: 47.62 },
      { province: "San Luis", value: 42.86 },
      { province: "San Juan", value: 57.14 },
      { province: "Santa Cruz", value: 57.14 },
      { province: "Santa Fe", value: 100.00 },
      { province: "Santiago del Estero", value: 14.29 },
      { province: "Tierra del Fuego", value: 33.33 },
      { province: "Tucumán", value: 42.86 },
      { province: "Nación", value: 100.00 },
    ],
  },
  {
    titulo: "NEPOTISMO",
    subTitulo: 'Normativa y sanciones previstas.',
    key: "nepotismo",
    id: 6,
    datos: [
      { province: "Buenos Aires", value: 90.91 },
      { province: "CABA", value: 100.00 },
      { province: "Catamarca", value: 0.00 },
      { province: "Chaco", value: 0.00 },
      { province: "Chubut", value: 0.00 },
      { province: "Córdoba", value: 0.00 },
      { province: "Corrientes", value: 0.00 },
      { province: "Entre Ríos", value: 90.91 },
      { province: "Formosa", value: 0.00 },
      { province: "Jujuy", value: 0.00 },
      { province: "La Pampa", value: 90.91 },
      { province: "La Rioja", value: 90.91 },
      { province: "Mendoza", value: 90.91 },
      { province: "Misiones", value: 100.00 },
      { province: "Neuquén", value: 0.00 },
      { province: "Río Negro", value: 0.00 },
      { province: "Salta", value: 0.00 },
      { province: "San Luis", value: 0.00 },
      { province: "San Juan", value: 0.00 },
      { province: "Santa Cruz", value: 90.91 },
      { province: "Santa Fe", value: 0.00 },
      { province: "Santiago del Estero", value: 0.00 },
      { province: "Tierra del Fuego", value: 0.00 },
      { province: "Tucumán", value: 0.00 },
      { province: "Nación", value: 90.91 },
    ],
  },
  {
    titulo: "CORRUPCIÓN",
    subTitulo: 'Organismos y herramientas de denuncias.',
    key: "corrupcion",
    id: 7,
    datos: [
      { province: "Buenos Aires", value: 66.67 },
      { province: "CABA", value: 100.00 },
      { province: "Catamarca", value: 0.00 },
      { province: "Chaco", value: 0.00 },
      { province: "Chubut", value: 100.00 },
      { province: "Córdoba", value: 0.00 },
      { province: "Corrientes", value: 0.00 },
      { province: "Entre Ríos", value: 33.33 },
      { province: "Formosa", value: 0.00 },
      { province: "Jujuy", value: 100.00 },
      { province: "La Pampa", value: 100.00 },
      { province: "La Rioja", value: 0.00 },
      { province: "Mendoza", value: 100.00 },
      { province: "Misiones", value: 0.00 },
      { province: "Neuquén", value: 100.00 },
      { province: "Río Negro", value: 0.00 },
      { province: "Salta", value: 0.00 },
      { province: "San Luis", value: 66.67 },
      { province: "San Juan", value: 0.00 },
      { province: "Santa Cruz", value: 0.00 },
      { province: "Santa Fe", value: 33.33 },
      { province: "Santiago del Estero", value: 0.00 },
      { province: "Tierra del Fuego", value: 100.00 },
      { province: "Tucumán", value: 0.00 },
      { province: "Nación", value: 100.00 },
    ],
  },
  {
    titulo: "GRUPO ACCESO",
    key: "grupoAcceso",
    id: 8,
    datos: [
      { province: "Buenos Aires", value: 71.50, opacity: 71.50 },
      { province: "CABA", value: 87.53, opacity: 87.53 },
      { province: "Catamarca", value: 69.80, opacity: 69.80 },
      { province: "Chaco", value: 88.56, opacity: 88.56 },
      { province: "Chubut", value: 70.69, opacity: 70.69 },
      { province: "Córdoba", value: 79.02, opacity: 79.02 },
      { province: "Corrientes", value: 64.87, opacity: 64.87 },
      { province: "Entre Ríos", value: 82.78, opacity: 82.78 },
      { province: "Formosa", value: 12.44, opacity: 12.44 },
      { province: "Jujuy", value: 64.00, opacity: 64.00 },
      { province: "La Pampa", value: 85.17, opacity: 85.17 },
      { province: "La Rioja", value: 54.28, opacity: 54.28 },
      { province: "Mendoza", value: 81.07, opacity: 81.07 },
      { province: "Misiones", value: 65.21, opacity: 65.21 },
      { province: "Neuquén", value: 65.55, opacity: 65.55 },
      { province: "Río Negro", value: 84.71, opacity: 84.71 },
      { province: "Salta", value: 46.59, opacity: 46.59 },
      { province: "San Luis", value: 51.94, opacity: 51.94 },
      { province: "San Juan", value: 65.77, opacity: 65.77 },
      { province: "Santa Cruz", value: 78.05, opacity: 78.05 },
      { province: "Santa Fe", value: 75.59, opacity: 75.59 },
      { province: "Santiago del Estero", value: 30.61, opacity: 30.61 },
      { province: "Tierra del Fuego", value: 93.49, opacity: 93.49 },
      { province: "Tucumán", value: 59.82, opacity: 59.82 },
      { province: "Nación", value: 96.67, opacity: 96.67 },
    ],
  },
  {
    titulo: "BOLETIN OFICIAL",
    subTitulo: 'Accesibilidad y experiencia de usuario.',
    key: "boletinOficial",
    id: 9,
    datos: [
      { province: "Buenos Aires", value: 92.50 },
      { province: "CABA", value: 95.00 },
      { province: "Catamarca", value: 90.00 },
      { province: "Chaco", value: 70.00 },
      { province: "Chubut", value: 92.50 },
      { province: "Córdoba", value: 100.00 },
      { province: "Corrientes", value: 90.00 },
      { province: "Entre Ríos", value: 92.50 },
      { province: "Formosa", value: 20.00 },
      { province: "Jujuy", value: 90.00 },
      { province: "La Pampa", value: 95.00 },
      { province: "La Rioja", value: 67.50 },
      { province: "Mendoza", value: 95.00 },
      { province: "Misiones", value: 70.00 },
      { province: "Neuquén", value: 92.50 },
      { province: "Río Negro", value: 90.00 },
      { province: "Salta", value: 100.00 },
      { province: "San Luis", value: 90.00 },
      { province: "San Juan", value: 90.00 },
      { province: "Santa Cruz", value: 95.00 },
      { province: "Santa Fe", value: 92.50 },
      { province: "Santiago del Estero", value: 45.00 },
      { province: "Tierra del Fuego", value: 100.00 },
      { province: "Tucumán", value: 92.50 },
      { province: "Nación", value: 100.00 },
    ],
  },
  {
    titulo: "PORTAL DE TRANSPARENCIA",
    subTitulo: 'Accesibilidad y actualización.',
    key: "portalTransparencia",
    id: 10,
    datos: [
      { province: "Buenos Aires", value: 32.14 },
      { province: "CABA", value: 100.00 },
      { province: "Catamarca", value: 100.00 },
      { province: "Chaco", value: 100.00 },
      { province: "Chubut", value: 67.86 },
      { province: "Córdoba", value: 100.00 },
      { province: "Corrientes", value: 0.00 },
      { province: "Entre Ríos", value: 67.86 },
      { province: "Formosa", value: 0.00 },
      { province: "Jujuy", value: 35.71 },
      { province: "La Pampa", value: 67.86 },
      { province: "La Rioja", value: 32.14 },
      { province: "Mendoza", value: 67.86 },
      { province: "Misiones", value: 67.86 },
      { province: "Neuquén", value: 0.00 },
      { province: "Río Negro", value: 100.00 },
      { province: "Salta", value: 0.00 },
      { province: "San Luis", value: 32.14 },
      { province: "San Juan", value: 32.14 },
      { province: "Santa Cruz", value: 67.86 },
      { province: "Santa Fe", value: 67.86 },
      { province: "Santiago del Estero", value: 0.00 },
      { province: "Tierra del Fuego", value: 100.00 },
      { province: "Tucumán", value: 100.00 },
      { province: "Nación", value: 100.00 },
    ],
  },
  {
    titulo: "ACCESO A LA INFORMACIÓN",
    subTitulo: 'Normativa y experiencia de usuario.',
    key: "accesoInformacion",
    id: 11,
    datos: [
      { province: "Buenos Aires", value: 82.22 },
      { province: "CABA", value: 100.00 },
      { province: "Catamarca", value: 60.00 },
      { province: "Chaco", value: 100.00 },
      { province: "Chubut", value: 60.00 },
      { province: "Córdoba", value: 80.00 },
      { province: "Corrientes", value: 80.00 },
      { province: "Entre Ríos", value: 80.00 },
      { province: "Formosa", value: 17.78 },
      { province: "Jujuy", value: 82.22 },
      { province: "La Pampa", value: 82.22 },
      { province: "La Rioja", value: 60.00 },
      { province: "Mendoza", value: 100.00 },
      { province: "Misiones", value: 62.22 },
      { province: "Neuquén", value: 80.00 },
      { province: "Río Negro", value: 82.22 },
      { province: "Salta", value: 60.00 },
      { province: "San Luis", value: 80.00 },
      { province: "San Juan", value: 0.00 },
      { province: "Santa Cruz", value: 60.00 },
      { province: "Santa Fe", value: 82.22 },
      { province: "Santiago del Estero", value: 60.00 },
      { province: "Tierra del Fuego", value: 80.00 },
      { province: "Tucumán", value: 0.00 },
      { province: "Nación", value: 100.00 },
    ],
  },
  {
    titulo: "RELACIÓN CON LA PRENSA",
    subTitulo: 'Herramientas y formas de contacto.',
    key: "relacionPrensa",
    id: 12,
    datos: [
      { province: "Buenos Aires", value: 82.35 },
      { province: "CABA", value: 41.18 },
      { province: "Catamarca", value: 11.76 },
      { province: "Chaco", value: 82.35 },
      { province: "Chubut", value: 58.82 },
      { province: "Córdoba", value: 17.65 },
      { province: "Corrientes", value: 100.00 },
      { province: "Entre Ríos", value: 94.12 },
      { province: "Formosa", value: 11.76 },
      { province: "Jujuy", value: 41.18 },
      { province: "La Pampa", value: 100.00 },
      { province: "La Rioja", value: 58.82 },
      { province: "Mendoza", value: 52.94 },
      { province: "Misiones", value: 58.82 },
      { province: "Neuquén", value: 100.00 },
      { province: "Río Negro", value: 58.82 },
      { province: "Salta", value: 17.65 },
      { province: "San Luis", value: 58.82 },
      { province: "San Juan", value: 100.00 },
      { province: "Santa Cruz", value: 94.12 },
      { province: "Santa Fe", value: 52.94 },
      { province: "Santiago del Estero", value: 11.76 },
      { province: "Tierra del Fuego", value: 94.12 },
      { province: "Tucumán", value: 41.18 },
      { province: "Nación", value: 82.35 },
    ],
  },
  {
    titulo: "GRUPO PRESUPUESTO",
    key: "grupoPresupuesto",
    id: 13,
    datos: [
      { province: "Buenos Aires", value: 75.84, opacity: 75.84 },
      { province: "CABA", value: 82.51, opacity: 82.51 },
      { province: "Catamarca", value: 61.67, opacity: 61.67 },
      { province: "Chaco", value: 35.00, opacity: 35.00 },
      { province: "Chubut", value: 62.51, opacity: 62.51 },
      { province: "Córdoba", value: 76.26, opacity: 76.26 },
      { province: "Corrientes", value: 21.67, opacity: 21.67 },
      { province: "Entre Ríos", value: 60.01, opacity: 60.01 },
      { province: "Formosa", value: 18.34, opacity: 18.34 },
      { province: "Jujuy", value: 16.67, opacity: 16.67 },
      { province: "La Pampa", value: 50.01, opacity: 50.01 },
      { province: "La Rioja", value: 50.01, opacity: 50.01 },
      { province: "Mendoza", value: 72.09, opacity: 72.09 },
      { province: "Misiones", value: 31.67, opacity: 31.67 },
      { province: "Neuquén", value: 65.42, opacity: 65.42 },
      { province: "Río Negro", value: 72.09, opacity: 72.09 },
      { province: "Salta", value: 45.00, opacity: 45.00 },
      { province: "San Luis", value: 23.34, opacity: 23.34 },
      { province: "San Juan", value: 50.01, opacity: 50.01 },
      { province: "Santa Cruz", value: 51.67, opacity: 51.67 },
      { province: "Santa Fe", value: 50.01, opacity: 50.01 },
      { province: "Santiago del Estero", value: 0.00, opacity: 0.00 },
      { province: "Tierra del Fuego", value: 62.09, opacity: 62.09 },
      { province: "Tucumán", value: 40.00, opacity: 40.00 },
      { province: "Nación", value: 72.09, opacity: 72.09 },
    ],
  },
  {
    titulo: "PORTAL DE COMPRAS",
    subTitulo: 'Accesibilidad a contrataciones y registros.',
    key: "portalCompras",
    id: 14,
    datos: [
      { province: "Buenos Aires", value: 80.00 },
      { province: "CABA", value: 85.00 },
      { province: "Catamarca", value: 100.00 },
      { province: "Chaco", value: 55.00 },
      { province: "Chubut", value: 50.00 },
      { province: "Córdoba", value: 50.00 },
      { province: "Corrientes", value: 0.00 },
      { province: "Entre Ríos", value: 80.00 },
      { province: "Formosa", value: 55.00 },
      { province: "Jujuy", value: 0.00 },
      { province: "La Pampa", value: 65.00 },
      { province: "La Rioja", value: 85.00 },
      { province: "Mendoza", value: 100.00 },
      { province: "Misiones", value: 30.00 },
      { province: "Neuquén", value: 65.00 },
      { province: "Río Negro", value: 85.00 },
      { province: "Salta", value: 85.00 },
      { province: "San Luis", value: 100.00 },
      { province: "San Juan", value: 70.00 },
      { province: "Santa Cruz", value: 55.00 },
      { province: "Santa Fe", value: 85.00 },
      { province: "Santiago del Estero", value: 0.00 },
      { province: "Tierra del Fuego", value: 55.00 },
      { province: "Tucumán", value: 85.00 },
      { province: "Nación", value: 85.00 },
    ],
  },
  {
    titulo: "PAUTA PUBLICITARIA",
    subTitulo: 'Normativa, accesibilidad.',
    key: "pautaPublicitaria",
    id: 15,
    datos: [
      { province: "Buenos Aires", value: 62.50 },
      { province: "CABA", value: 62.50 },
      { province: "Catamarca", value: 0.00 },
      { province: "Chaco", value: 0.00 },
      { province: "Chubut", value: 37.50 },
      { province: "Córdoba", value: 93.75 },
      { province: "Corrientes", value: 0.00 },
      { province: "Entre Ríos", value: 0.00 },
      { province: "Formosa", value: 0.00 },
      { province: "Jujuy", value: 0.00 },
      { province: "La Pampa", value: 0.00 },
      { province: "La Rioja", value: 0.00 },
      { province: "Mendoza", value: 31.25 },
      { province: "Misiones", value: 0.00 },
      { province: "Neuquén", value: 31.25 },
      { province: "Río Negro", value: 31.25 },
      { province: "Salta", value: 0.00 },
      { province: "San Luis", value: 0.00 },
      { province: "San Juan", value: 0.00 },
      { province: "Santa Cruz", value: 0.00 },
      { province: "Santa Fe", value: 0.00 },
      { province: "Santiago del Estero", value: 0.00 },
      { province: "Tierra del Fuego", value: 31.25 },
      { province: "Tucumán", value: 0.00 },
      { province: "Nación", value: 31.25 },
    ],
  },
  {
    titulo: "PRESUPUESTO",
    subTitulo: 'Accesibilidad y actualización.',
    key: "presupuesto",
    id: 16,
    datos: [
      { province: "Buenos Aires", value: 85.00 },
      { province: "CABA", value: 100.00 },
      { province: "Catamarca", value: 85.00 },
      { province: "Chaco", value: 50.00 },
      { province: "Chubut", value: 100.00 },
      { province: "Córdoba", value: 85.00 },
      { province: "Corrientes", value: 65.00 },
      { province: "Entre Ríos", value: 100.00 },
      { province: "Formosa", value: 0.00 },
      { province: "Jujuy", value: 50.00 },
      { province: "La Pampa", value: 85.00 },
      { province: "La Rioja", value: 65.00 },
      { province: "Mendoza", value: 85.00 },
      { province: "Misiones", value: 65.00 },
      { province: "Neuquén", value: 100.00 },
      { province: "Río Negro", value: 100.00 },
      { province: "Salta", value: 50.00 },
      { province: "San Luis", value: 50.00 },
      { province: "San Juan", value: 0.00 },
      { province: "Santa Cruz", value: 100.00 },
      { province: "Santa Fe", value: 65.00 },
      { province: "Santiago del Estero", value: 0.00 },
      { province: "Tierra del Fuego", value: 100.00 },
      { province: "Tucumán", value: 35.00 },
      { province: "Nación", value: 100.00 },
    ],
  },
  {
    titulo: "RANKING GENERAL",
    subTitulo: '', 
    key: "rankingGeneral",
    id: 16,
    datos: [
      { province: "Buenos Aires", value: 63.85, ranking: 5 },
      { province: "CABA", value: 85.02, ranking: 1 },
      { province: "Catamarca", value: 47.98, ranking: 17 },
      { province: "Chaco", value: 58.35, ranking: 14 },
      { province: "Chubut", value: 61.66, ranking: 10 },
      { province: "Córdoba", value: 62.39, ranking: 9 },
      { province: "Corrientes", value: 42.42, ranking: 21 },
      { province: "Entre Ríos", value: 63.26, ranking: 7 },
      { province: "Formosa", value: 12.83, ranking: 25 },
      { province: "Jujuy", value: 50.40, ranking: 15 },
      { province: "La Pampa", value: 63.79, ranking: 6 },
      { province: "La Rioja", value: 46.95, ranking: 18 },
      { province: "Mendoza", value: 77.18, ranking: 3 },
      { province: "Misiones", value: 41.63, ranking: 19 },
      { province: "Neuquén", value: 59.30, ranking: 13 },
      { province: "Río Negro", value: 68.16, ranking: 4 },
      { province: "Salta", value: 37.87, ranking: 22 },
      { province: "San Luis", value: 47.41, ranking: 23 },
      { province: "San Juan", value: 38.66, ranking: 16 },
      { province: "Santa Cruz", value: 60.33, ranking: 11 },
      { province: "Santa Fe", value: 59.83, ranking: 12 },
      { province: "Santiago del Estero", value: 20.79, ranking: 24 },
      { province: "Tierra del Fuego", value: 62.99, ranking: 8 },
      { province: "Tucumán", value: 40.28, ranking: 20 },
      { province: "Nación", value: 83.90, ranking: 2 },
    ],
  },
];
