export const selectProvinceOptions = [
    { label: "Buenos Aires", value: "Buenos Aires" },
    { label: "Ciudad Autónoma de Buenos Aires", value: "CABA" },
    { label: "Catamarca", value: "Catamarca" },
    { label: "Chaco", value: "Chaco" },
    { label: "Chubut", value: "Chubut" },
    { label: "Córdoba", value: "Cordoba" },
    { label: "Corrientes", value: "Corrientes" },
    { label: "Entre Ríos", value: "Entre Rios" },
    { label: "Formosa", value: "Formosa" },
    { label: "Jujuy", value: "Jujuy" },
    { label: "La Pampa", value: "La Pampa" },
    { label: "La Rioja", value: "La Rioja" },
    { label: "Mendoza", value: "Mendoza" },
    { label: "Misiones", value: "Misiones" },
    { label: "Neuquén", value: "Neuquen" },
    { label: "Río Negro", value: "Rio Negro" },
    { label: "Salta", value: "Salta" },
    { label: "San Luis", value: "San Luis" },
    { label: "San Juan", value: "San Juan" },
    { label: "Santa Cruz", value: "Santa Cruz" },
    { label: "Santa Fe", value: "Santa Fe" },
    { label: "Santiago del Estero", value: "Santiago del Estero" },
    { label: "Tierra del Fuego", value: "Tierra del Fuego" },
    { label: "Tucumán", value: "Tucuman" },
    { label: "Nación", value: "Nacion" },
]